export const CURATED_SEED_ITEMS = [
  {
    id: 'google-turboquant-2026-03-24',
    title: 'Google apresenta TurboQuant e promete até 6x menos uso de memória em IA',
    slug: 'google-turboquant-ia-6x-menos-memoria',
    url: 'https://www.technetgame.com.br/google-turboquant-ia-6x-menos-memoria.html',
    summary: 'Reportagem editorial própria do TechNetGame sobre a tecnologia TurboQuant, apresentada como avanço de compressão de KV Cache para inferência mais leve e rápida.',
    source: 'TechNetGame',
    sourceSlug: 'technetgame-editorial',
    sourceUrl: 'https://www.technetgame.com.br/tecnologia.html',
    category: 'technology',
    tags: ['google', 'turboquant', 'kv cache', 'ai', 'editorial'],
    language: 'pt-br',
    publishedAt: '2026-03-24T12:00:00.000Z',
    image: 'https://www.technetgame.com.br/assets/img/google-turboquant.jpg',
    isOfficial: false,
    pinned: true
  },
  {
    id: 'apple-50-years-thinking-different-2026-03-12',
    title: 'Apple celebra 50 anos com ações globais e reforço de marca',
    slug: 'apple-celebra-50-anos-com-acoes-globais-e-reforco-de-marca',
    url: 'https://www.apple.com/newsroom/2026/03/apple-to-celebrate-50-years-of-thinking-different/',
    summary: 'Item semente mantido para evitar homepage vazia: Apple destacou as comemorações globais de 50 anos em março de 2026.',
    source: 'Apple Newsroom',
    sourceSlug: 'apple-newsroom',
    sourceUrl: 'https://www.apple.com/newsroom/',
    category: 'technology',
    tags: ['apple', 'brand', 'official', 'seed'],
    language: 'en',
    publishedAt: '2026-03-12T00:00:00.000Z',
    image: null,
    isOfficial: true,
    pinned: true
  },
  {
    id: 'apple-iphone-17e-2026-03-02',
    title: 'Apple apresenta o iPhone 17e com foco em valor e maior armazenamento inicial',
    slug: 'apple-apresenta-o-iphone-17e-com-foco-em-valor-e-maior-armazenamento-inicial',
    url: 'https://www.apple.com/newsroom/2026/03/apple-introduces-iphone-17e/',
    summary: 'Item semente mantido na editoria de tecnologia: a Apple anunciou o iPhone 17e em 2 de março de 2026.',
    source: 'Apple Newsroom',
    sourceSlug: 'apple-newsroom',
    sourceUrl: 'https://www.apple.com/newsroom/',
    category: 'technology',
    tags: ['apple', 'iphone', 'official', 'seed'],
    language: 'en',
    publishedAt: '2026-03-02T00:00:00.000Z',
    image: null,
    isOfficial: true,
    pinned: true
  },
  {
    id: 'apple-macbook-air-m5-2026-03-03',
    title: 'Apple lança novo MacBook Air com M5 e foco ampliado em IA',
    slug: 'apple-lanca-novo-macbook-air-com-m5-e-foco-ampliado-em-ia',
    url: 'https://www.apple.com/newsroom/2026/03/apple-introduces-the-new-macbook-air-with-m5/',
    summary: 'Notícia semente para tecnologia: novo MacBook Air com M5, mais desempenho e recursos de IA.',
    source: 'Apple Newsroom',
    sourceSlug: 'apple-newsroom',
    sourceUrl: 'https://www.apple.com/newsroom/',
    category: 'technology',
    tags: ['apple', 'macbook', 'official', 'seed'],
    language: 'en',
    publishedAt: '2026-03-03T00:00:00.000Z',
    image: null,
    isOfficial: true,
    pinned: true
  },
  {
    id: 'google-pixel-drop-2026-03-03',
    title: 'Google libera March Pixel Drop com novas funções de personalização e IA',
    slug: 'google-libera-march-pixel-drop-com-novas-funcoes-de-personalizacao-e-ia',
    url: 'https://blog.google/products-and-platforms/devices/pixel/march-2026-pixel-drop/',
    summary: 'Item semente de Big Tech: o Pixel Drop de março de 2026 trouxe recursos novos de IA, segurança e experiência Pixel.',
    source: 'Google Blog',
    sourceSlug: 'google-blog',
    sourceUrl: 'https://blog.google/',
    category: 'technology',
    tags: ['google', 'pixel', 'ai', 'seed'],
    language: 'en',
    publishedAt: '2026-03-03T00:00:00.000Z',
    image: null,
    isOfficial: true,
    pinned: true
  },
  {
    id: 'google-workspace-gemini-2026-03-10',
    title: 'Google amplia o Gemini no Workspace com novidades para Docs, Sheets, Slides e Drive',
    slug: 'google-amplia-o-gemini-no-workspace-com-novidades-para-docs-sheets-slides-e-drive',
    url: 'https://blog.google/products-and-platforms/products/workspace/gemini-workspace-updates-march-2026/',
    summary: 'Cobertura semente em IA e produtividade: o Google detalhou novos recursos do Gemini para o Workspace em 10 de março de 2026.',
    source: 'Google Blog',
    sourceSlug: 'google-blog',
    sourceUrl: 'https://blog.google/',
    category: 'technology',
    tags: ['google', 'gemini', 'workspace', 'seed'],
    language: 'en',
    publishedAt: '2026-03-10T00:00:00.000Z',
    image: null,
    isOfficial: true,
    pinned: true
  },
  {
    id: 'google-wiz-acquisition-2026-03-11',
    title: 'Google conclui a aquisição da Wiz para reforçar segurança em nuvem e IA',
    slug: 'google-conclui-a-aquisicao-da-wiz-para-reforcar-seguranca-em-nuvem-e-ia',
    url: 'https://blog.google/innovation-and-ai/infrastructure-and-cloud/google-cloud/wiz-acquisition/',
    summary: 'Item semente de tecnologia e segurança: o Google anunciou a conclusão da compra da Wiz em 11 de março de 2026.',
    source: 'Google Blog',
    sourceSlug: 'google-blog',
    sourceUrl: 'https://blog.google/',
    category: 'security',
    tags: ['google', 'wiz', 'cloud security', 'seed'],
    language: 'en',
    publishedAt: '2026-03-11T00:00:00.000Z',
    image: null,
    isOfficial: true,
    pinned: true
  },
  {
    id: 'sony-psplus-march-2026-2026-03-11',
    title: 'PlayStation Plus de março destaca Space Marine 2, Madden NFL 26, Persona 5 Royal e Blasphemous 2',
    slug: 'playstation-plus-de-marco-destaca-space-marine-2-madden-nfl-26-persona-5-royal-e-blasphemous-2',
    url: 'https://blog.playstation.com/2026/03/11/playstation-plus-game-catalog-for-march-warhammer-40000-space-marine-2-ea-sports-madden-nfl-26-persona-5-royal-blasphemous-2-and-more/',
    summary: 'Item semente para Sony/PlayStation com lineup oficial do catálogo de março.',
    source: 'PlayStation Blog',
    sourceSlug: 'playstation-blog',
    sourceUrl: 'https://blog.playstation.com/',
    category: 'sony',
    tags: ['sony', 'playstation', 'ps plus', 'seed'],
    language: 'en',
    publishedAt: '2026-03-11T00:00:00.000Z',
    image: null,
    isOfficial: true,
    pinned: true
  },
  {
    id: 'sony-capcom-spotlight-pragmata-2026-03-05',
    title: 'Capcom Spotlight de março confirma Pragmata para 17 de abril e traz novidades de Street Fighter 6',
    slug: 'capcom-spotlight-de-marco-confirma-pragmata-para-17-de-abril-e-traz-novidades-de-street-fighter-6',
    url: 'https://blog.playstation.com/2026/03/05/capcom-spotlight-march-2026-recap-pragmata-launches-april-17-alex-joins-street-fighter-6-and-more/',
    summary: 'Semente de pré-estreia em PlayStation: Pragmata ganhou nova data e destaque editorial em março de 2026.',
    source: 'PlayStation Blog',
    sourceSlug: 'playstation-blog',
    sourceUrl: 'https://blog.playstation.com/',
    category: 'sony',
    tags: ['sony', 'pragmata', 'pre-release', 'seed'],
    language: 'en',
    publishedAt: '2026-03-05T00:00:00.000Z',
    image: null,
    isOfficial: true,
    pinned: true
  },
  {
    id: 'xbox-next-week-2026-03-13',
    title: 'Next Week on Xbox destaca os lançamentos de 16 a 20 de março',
    slug: 'next-week-on-xbox-destaca-os-lancamentos-de-16-a-20-de-marco',
    url: 'https://news.xbox.com/en-us/2026/03/13/next-week-on-xbox-new-games-for-march-16-to-20/',
    summary: 'Item semente para Microsoft/Xbox com calendário oficial de lançamentos da semana seguinte.',
    source: 'Xbox Wire',
    sourceSlug: 'xbox-wire',
    sourceUrl: 'https://news.xbox.com/en-us/',
    category: 'microsoft',
    tags: ['microsoft', 'xbox', 'launches', 'seed'],
    language: 'en',
    publishedAt: '2026-03-13T00:00:00.000Z',
    image: null,
    isOfficial: true,
    pinned: true
  },
  {
    id: 'xbox-black-ops-royale-2026-03-13',
    title: 'Xbox Wire detalha como Black Ops Royale tenta reviver uma experiência clássica de Call of Duty',
    slug: 'xbox-wire-detalha-como-black-ops-royale-tenta-reviver-uma-experiencia-classica-de-call-of-duty',
    url: 'https://news.xbox.com/en-us/2026/03/13/how-black-ops-royale-reviving-fan-favorite-call-of-duty-experience/',
    summary: 'Semente editorial para a área Microsoft/Xbox e radar de shooters competitivos.',
    source: 'Xbox Wire',
    sourceSlug: 'xbox-wire',
    sourceUrl: 'https://news.xbox.com/en-us/',
    category: 'microsoft',
    tags: ['microsoft', 'xbox', 'call of duty', 'seed'],
    language: 'en',
    publishedAt: '2026-03-13T00:00:00.000Z',
    image: null,
    isOfficial: true,
    pinned: true
  },
  {
    id: 'nintendo-march-games-2026-03-09',
    title: 'Nintendo destaca os jogos que chegam em março de 2026 no ecossistema Switch',
    slug: 'nintendo-destaca-os-jogos-que-chegam-em-marco-de-2026-no-ecossistema-switch',
    url: 'https://www.nintendo.com/us/whatsnew/see-what-games-are-arriving-this-march-2026/',
    summary: 'Item semente para Nintendo com lista oficial de lançamentos do mês.',
    source: 'Nintendo News',
    sourceSlug: 'nintendo-news',
    sourceUrl: 'https://www.nintendo.com/us/whatsnew/',
    category: 'nintendo',
    tags: ['nintendo', 'switch', 'launches', 'seed'],
    language: 'en',
    publishedAt: '2026-03-09T00:00:00.000Z',
    image: null,
    isOfficial: true,
    pinned: true
  },
  {
    id: 'nintendo-monster-hunter-stories-3-2026-03-13',
    title: 'Monster Hunter Stories 3: Twisted Reflection entra em destaque no noticiário da Nintendo',
    slug: 'monster-hunter-stories-3-twisted-reflection-entra-em-destaque-no-noticiario-da-nintendo',
    url: 'https://www.nintendo.com/us/whatsnew/see-what-games-are-arriving-this-march-2026/',
    summary: 'Item semente de pré-estreia e catálogo para Nintendo/Switch 2.',
    source: 'Nintendo News',
    sourceSlug: 'nintendo-news',
    sourceUrl: 'https://www.nintendo.com/us/whatsnew/',
    category: 'nintendo',
    tags: ['nintendo', 'monster hunter stories', 'switch 2', 'seed'],
    language: 'en',
    publishedAt: '2026-03-13T00:00:00.000Z',
    image: null,
    isOfficial: true,
    pinned: true
  },
  {
    id: 'valve-steam-deck-client-update-2026-03-09',
    title: 'Steam Deck Client recebe atualização estável em 9 de março',
    slug: 'steam-deck-client-recebe-atualizacao-estavel-em-9-de-marco',
    url: 'https://store.steampowered.com/news/app/1675200/view/502851820603836936',
    summary: 'Item semente para a área Valve/Steam: atualização oficial do cliente do Steam Deck no canal estável.',
    source: 'Steam News',
    sourceSlug: 'steam-news',
    sourceUrl: 'https://store.steampowered.com/news/',
    category: 'valve',
    tags: ['valve', 'steam deck', 'client update', 'seed'],
    language: 'en',
    publishedAt: '2026-03-09T00:00:00.000Z',
    image: null,
    isOfficial: true,
    pinned: true
  },
  {
    id: 'valve-sales-events-h1-2026-2025-08-08',
    title: 'Valve mantém publicada a agenda oficial de promoções e eventos do primeiro semestre de 2026',
    slug: 'valve-mantem-publicada-a-agenda-oficial-de-promocoes-e-eventos-do-primeiro-semestre-de-2026',
    url: 'https://store.steampowered.com/news/group/4145017/view/532102384016426891',
    summary: 'Item semente mantido para não deixar a área Valve vazia: agenda oficial de eventos e promoções do Steam para o primeiro semestre de 2026.',
    source: 'Steam News',
    sourceSlug: 'steam-news',
    sourceUrl: 'https://store.steampowered.com/news/',
    category: 'valve',
    tags: ['valve', 'steam sales', 'official', 'seed'],
    language: 'en',
    publishedAt: '2025-08-08T00:00:00.000Z',
    image: null,
    isOfficial: true,
    pinned: true
  },
  {
    id: 'nvidia-gfn-march-games-2026-03-12',
    title: 'GeForce NOW anuncia 15 novos jogos para março',
    slug: 'geforce-now-anuncia-15-novos-jogos-para-marco',
    url: 'https://nvidianews.nvidia.com/news/latest',
    summary: 'Item semente de hardware e cloud gaming baseado na cobertura mais recente do NVIDIA Newsroom.',
    source: 'NVIDIA Newsroom',
    sourceSlug: 'nvidia-newsroom',
    sourceUrl: 'https://nvidianews.nvidia.com/',
    category: 'hardware',
    tags: ['nvidia', 'geforce now', 'cloud gaming', 'seed'],
    language: 'en',
    publishedAt: '2026-03-12T00:00:00.000Z',
    image: null,
    isOfficial: true,
    pinned: true
  },
  {
    id: 'nvidia-nemotron-3-super-2026-03-11',
    title: 'NVIDIA apresenta o Nemotron 3 Super com foco em throughput para IA agentiva',
    slug: 'nvidia-apresenta-o-nemotron-3-super-com-foco-em-throughput-para-ia-agentiva',
    url: 'https://nvidianews.nvidia.com/',
    summary: 'Cobertura semente de IA e infraestrutura, útil para manter a editoria aquecida mesmo sem atualização imediata do feed.',
    source: 'NVIDIA Newsroom',
    sourceSlug: 'nvidia-newsroom',
    sourceUrl: 'https://nvidianews.nvidia.com/',
    category: 'hardware',
    tags: ['nvidia', 'ai', 'infrastructure', 'seed'],
    language: 'en',
    publishedAt: '2026-03-11T00:00:00.000Z',
    image: null,
    isOfficial: true,
    pinned: true
  },
  {
    id: 'cisa-kev-2026-03-11',
    title: 'CISA adiciona nova vulnerabilidade explorada ao catálogo KEV em 11 de março',
    slug: 'cisa-adiciona-nova-vulnerabilidade-explorada-ao-catalogo-kev-em-11-de-marco',
    url: 'https://www.cisa.gov/news-events/alerts/2026/03/11/cisa-adds-one-known-exploited-vulnerability-catalog',
    summary: 'Item semente para segurança: alerta operacional da CISA com atualização do catálogo Known Exploited Vulnerabilities.',
    source: 'CISA',
    sourceSlug: 'cisa-news',
    sourceUrl: 'https://www.cisa.gov/news-events/cybersecurity-advisories',
    category: 'security',
    tags: ['cisa', 'kev', 'security', 'seed'],
    language: 'en',
    publishedAt: '2026-03-11T00:00:00.000Z',
    image: null,
    isOfficial: true,
    pinned: true
  },
  {
    id: 'cisa-kev-2026-03-03',
    title: 'CISA adiciona duas vulnerabilidades exploradas ao catálogo KEV em 3 de março',
    slug: 'cisa-adiciona-duas-vulnerabilidades-exploradas-ao-catalogo-kev-em-3-de-marco',
    url: 'https://www.cisa.gov/news-events/alerts/2026/03/03/cisa-adds-two-known-exploited-vulnerabilities-catalog',
    summary: 'Segundo item semente de segurança para manter a seção ativa com alertas oficiais recentes.',
    source: 'CISA',
    sourceSlug: 'cisa-news',
    sourceUrl: 'https://www.cisa.gov/news-events/cybersecurity-advisories',
    category: 'security',
    tags: ['cisa', 'vulnerabilities', 'official', 'seed'],
    language: 'en',
    publishedAt: '2026-03-03T00:00:00.000Z',
    image: null,
    isOfficial: true,
    pinned: true
  }
];
